### ISSUE TITLE
Mismatch Types

### ISSUE THREAD

**Issue by tance77** [timfish/sentry-tauri#17]
In Sentry `0.35` it seems like they are returning a `ClientGuard` now and this plugin wants a `&Client`

for this chunk of code

```rs
 tauri::Builder::default()
        .plugin(tauri_plugin_sentry::init(&client)) //new Sentry 0.35 wants a ClientGuard
```

**Comment by timfish** [comment]
I've just published a new release which updates Sentry to 0.35
