### ISSUE TITLE
App doesn't exit on Windows

### ISSUE THREAD

**Issue by dceddia** [timfish/sentry-tauri#2]
Thanks for putting this together! I got it wired up and it's awesome to be able to see crash reports.

I hit upon a weird issue where the app doesn't stop running after process::exit. The relevant bit of my code, I think, is here:

```rust
.on_window_event(|e| match e.event() {
    WindowEvent::CloseRequested { .. } => {
        let label = e.window().label();

        // Only quit if it's the "main" window that was closed
        if label == &"main".to_string() {
            let app_handle = e.window().app_handle();
            // AppHandle::exit can't be called on the main thread apparently
            // https://github.com/tauri-apps/tauri/discussions/3555
            std::thread::spawn(move || {
                app_handle.exit(0);
            });
        }
    },
    _ => {}
```

This is causing the app process to exit, but the sentry_rust_minidump server process is still running, polling for crashes:

<img width="1229" alt="Screen Shot 2022-07-18 at 7 56 43 PM" src="https://user-images.githubusercontent.com/505704/179636369-0c3d4d0b-e3b0-4390-94ca-a6473dec075e.png">

It looks like there's a `shutdown` boolean that would get it to stop, but I'm not sure how to set it.

**Comment by timfish** [comment]
I've got a feeling this has been fixed by https://github.com/EmbarkStudios/crash-handling/pull/41 which is not been published in a release yet!

**Comment by timfish** [comment]
Jake who created the `crash-handler` crate pointed out we were missing the disconnect hook. I've just release 0.1.2 with this fix. Let me know if it fixes the issue!

**Comment by dceddia** [comment]
Awesome, that fixed it! Thanks!
