### ISSUE TITLE
Update sentry dependency to newer release

### ISSUE THREAD

**Issue by GeckoEidechse** [timfish/sentry-tauri#4]
From what [I found in my own project](https://github.com/R2NorthstarTools/FlightCore/pull/174), `0.27` is marked as outdated in the Sentry web dashboard. As such it would make sense to bump the used sentry version ^^

**Comment by GeckoEidechse** [comment]
Additionally as I learned in https://github.com/getsentry/sentry/issues/45116 only version `0.29.3` or higher of the `sentry` crate contain the necessary info associate native stacktraces with Windows debug symbols.

As such `0.29.3` should be the minimum target as otherwise native crashes are impossible to debug on Windows.

**Comment by timfish** [comment]
I'll get onto this when I'm back from vacation in around a week!

**Comment by tance77** [comment]
> I'll get onto this when I'm back from vacation in around a week!

Any update on this ? @timfish

**Comment by timfish** [comment]
Sorry for the delay, I've been busy with other things but today I found some time to finish the refactor I'd started and release 0.2.0.

Since `sentry` doesn't have a major version yet and you need to use a specific minor version of `sentry`, I now re-export it which means you only need to depend on this crate.

The usage now boils down to:
```toml
[dependencies]
sentry-tauri = "0.2"
```

```rust
fn main() {
    let client = sentry_tauri::sentry::init((
        "__YOUR_DSN__",
        sentry_tauri::sentry::ClientOptions {
            release: sentry_tauri::sentry::release_name!(),
            ..Default::default()
        },
    ));

    // Everything before here runs in both app and crash reporter processes
    let _guard = sentry_tauri::minidump::init(&client);
    // Everything after here runs in only the app process

    tauri::Builder::default()
        .plugin(sentry_tauri::plugin())
        .run(tauri::generate_context!())
        .expect("error while running tauri app");
}
```
